// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Loads .env.development.local (the local Docker Postgres, per ADR-0000) rather than
// the bare .env, because `neon deploy` / `neon env pull` overwrite .env wholesale with
// the Neon branch's own DATABASE_URL every time Neon services change.
import { config } from "dotenv";
config({ path: ".env.development.local" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
